### ISSUE TITLE
cuda相关报错

### ISSUE THREAD

**Issue by I6Redamancy** [Jittor/jittor#317]
## Describe the bug
在运行python3.9 -m jittor.test.test_resnet  时运行结果如下：
```
[i 0422 17:52:01.626586 96 compiler.py:951] Jittor(1.3.3.0) src: /home/lfq/.local/lib/python3.9/site-packages/jittor
[i 0422 17:52:01.628902 96 compiler.py:952] g++ at /usr/bin/g++(7.5.0)
[i 0422 17:52:01.628981 96 compiler.py:953] cache_path: /home/lfq/.cache/jittor/jt1.3.3/g++7.5.0/py3.9.5/Linux-5.10.16.x76/IntelRCoreTMi7x5f/default
[i 0422 17:52:02.514748 96 install_cuda.py:53] cuda_driver_version: [11, 6]
[i 0422 17:52:02.517417 96 __init__.py:411] Found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc(11.2.152) at /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc.
[i 0422 17:52:02.574761 96 __init__.py:411] Found addr2line(2.34) at /usr/bin/addr2line.
[i 0422 17:52:02.668945 96 compiler.py:1006] cuda key:cu11.2.152_sm_
[i 0422 17:52:02.844678 96 __init__.py:227] Total mem: 12.32GB, using 4 procs for compiling.
[e 0422 17:52:02.891332 96 cache_compile.cc:191] Load JT env ok: JT_SYNC 1
Compiling jittor_core(148/148) used: 2.132s eta: 0.000s
[i 0422 17:52:05.327819 96 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0422 17:52:05.327861 96 jit_compiler.cc:31] Load nvcc_path: /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc
[i 0422 17:52:05.423064 96 py_var_tracer.cc:22] Load trace_py_var: 3
[i 0422 17:52:05.423127 96 init.cc:62] Found cuda archs: [61,]
[i 0422 17:52:05.542844 96 compile_extern.py:516] mpicc not found, distribution disabled.
[w 0422 17:52:05.564236 96 compile_extern.py:200] CUDA related path found in LD_LIBRARY_PATH or PATH(['', '/home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/games', '/usr/local/games', '/usr/lib/wsl/lib', '/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin', '/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/libnvvp', '/mnt/c/Program Files/NVIDIA Corporation/Nsight Compute 2022.1.1/', '/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR', '/mnt/c/Program Files/CMake/bin', '/mnt/c/Program Files/nodejs/', '/mnt/c/MinGW/bin', '/mnt/c/Strawberry/c/bin', '/mnt/c/Strawberry/perl/bin', '/mnt/c/Users/86185/miniconda3', '/mnt/c/Users/86185/miniconda3/Scripts', '/mnt/c/Users/86185/miniconda3/envs/pytorch', '/mnt/c/Users/86185/miniconda3/envs/pytorch/Scripts', '/mnt/c/Windows/System32/WindowsPowerShell/v1.0', '/mnt/c/Windows/System32', '/mnt/c/Users/86185/AppData/Local/Programs/Microsoft VS Code/bin', '/snap/bin']), This path may cause jittor found the wrong libs, please unset LD_LIBRARY_PATH and remove cuda lib path in Path.
[i 0422 17:52:05.582730 96 compile_extern.py:30] found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/include/cublas.h
[i 0422 17:52:05.588138 96 compile_extern.py:30] found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64/libcublas.so
[i 0422 17:52:05.588245 96 compile_extern.py:30] found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64/libcublasLt.so.11      
[i 0422 17:52:05.858695 96 compile_extern.py:30] found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/include/cudnn.h
[i 0422 17:52:05.865239 96 compile_extern.py:30] found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64/libcudnn.so.8
[i 0422 17:52:05.865358 96 compile_extern.py:30] found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64/libcudnn_ops_infer.so.8[i 0422 17:52:05.870967 96 compile_extern.py:30] found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64/libcudnn_ops_train.so.8[i 0422 17:52:05.871698 96 compile_extern.py:30] found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64/libcudnn_cnn_infer.so.8[i 0422 17:52:05.891800 96 compile_extern.py:30] found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64/libcudnn_cnn_train.so.8[i 0422 17:52:06.246796 96 compile_extern.py:30] found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/include/curand.h
[i 0422 17:52:06.254802 96 compile_extern.py:30] found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64/libcurand.so
[i 0422 17:52:06.276991 96 compile_extern.py:30] found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/include/cufft.h
[i 0422 17:52:06.288450 96 compile_extern.py:30] found /home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64/libcufft.so
[i 0422 17:52:06.328260 96 cuda_flags.cc:32] CUDA enabled.
E[i 0422 17:52:20.816876 96 cuda_flags.cc:32] CUDA enabled.
[i 0422 17:53:03.639868 96 cuda_flags.cc:32] CUDA enabled.
F
======================================================================
ERROR: test_resnet (__main__.TestResnetFp16)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py", line 123, in inner
    ret = func(*args, **kw)
  File "/home/lfq/.local/lib/python3.9/site-packages/jittor/test/test_resnet.py", line 81, in test_resnet
    output = mnist_net(data)
  File "/home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py", line 811, in __call__
    return self.execute(*args, **kw)
  File "/home/lfq/.local/lib/python3.9/site-packages/jittor/test/test_resnet.py", line 34, in execute
    x = self.model(x)
  File "/home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py", line 811, in __call__
    return self.execute(*args, **kw)
  File "/home/lfq/.local/lib/python3.9/site-packages/jittor/models/resnet.py", line 152, in execute
    return self._forward_impl(x)
  File "/home/lfq/.local/lib/python3.9/site-packages/jittor/models/resnet.py", line 139, in _forward_impl
    x = self.bn1(x)
  File "/home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py", line 811, in __call__
    return self.execute(*args, **kw)
  File "/home/lfq/.local/lib/python3.9/site-packages/jittor/nn.py", line 591, in execute
    self.running_mean.update(self.running_mean +
RuntimeError: [f 0422 17:52:20.083396 96 executor.cc:657] 
Execute fused operator(125/778) failed.
[JIT Source]: /home/lfq/.cache/jittor/jt1.3.3/g++7.5.0/py3.9.5/Linux-5.10.16.x76/IntelRCoreTMi7x5f/default/cu11.2.152_sm_/jit/_opkey0_broadcast_to_Tx_float32__DIM_7__BCAST_19___opkey1_reindex_Tx_float32__XDIM_4__YDIM___hash_dca1e8276a7e9e2c_op.cc
[OP TYPE]: fused_op:( broadcast_to, reindex, binary.multiply, reduce.add,)
[Input]: float32[64,64,3,3,], float32[100,64,56,56,],
[Output]: float32[100,64,56,56,],
[Async Backtrace]: ---
     /usr/lib/python3.9/runpy.py:197 <_run_module_as_main>
     /usr/lib/python3.9/runpy.py:87 <_run_code>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/test/test_resnet.py:151 <<module>>
     /usr/lib/python3.9/unittest/main.py:101 <__init__>
     /usr/lib/python3.9/unittest/main.py:271 <runTests>
     /usr/lib/python3.9/unittest/runner.py:176 <run>
     /usr/lib/python3.9/unittest/suite.py:84 <__call__>
     /usr/lib/python3.9/unittest/suite.py:122 <run>
     /usr/lib/python3.9/unittest/suite.py:84 <__call__>
     /usr/lib/python3.9/unittest/suite.py:122 <run>
     /usr/lib/python3.9/unittest/case.py:653 <__call__>
     /usr/lib/python3.9/unittest/case.py:593 <run>
     /usr/lib/python3.9/unittest/case.py:550 <_callTestMethod>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py:123 <inner>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/test/test_resnet.py:81 <test_resnet>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py:811 <__call__>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/test/test_resnet.py:34 <execute>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py:811 <__call__>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/models/resnet.py:152 <execute>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/models/resnet.py:142 <_forward_impl>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py:811 <__call__>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/nn.py:2054 <execute>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py:811 <__call__>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/models/resnet.py:49 <execute>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py:811 <__call__>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/nn.py:847 <execute>
[Reason]: [f 0422 17:52:20.083159 96 helper_cuda.h:128] CUDA error at /home/lfq/.local/lib/python3.9/site-packages/jittor/src/mem/allocator/cuda_managed_allocator.cc:23  code=2( cudaErrorMemoryAllocation ) cudaMallocManaged(&ptr, size)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py", line 123, in inner
    ret = func(*args, **kw)
  File "/home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py", line 143, in __exit__
    setattr(flags, k, v)
RuntimeError: [f 0422 17:52:20.805644 96 executor.cc:657] 
Execute fused operator(80/1485) failed.
[JIT Source]: /home/lfq/.cache/jittor/jt1.3.3/g++7.5.0/py3.9.5/Linux-5.10.16.x76/IntelRCoreTMi7x5f/default/cu11.2.152_sm_/jit/_opkey0_broadcast_to_Tx_float32__DIM_7__BCAST_19___opkey1_reindex_Tx_float32__XDIM_4__YDIM___hash_dca1e8276a7e9e2c_op.cc
[OP TYPE]: fused_op:( broadcast_to, reindex, binary.multiply, reduce.add,)
[Input]: float32[64,64,3,3,], float32[100,64,56,56,],
[Output]: float32[100,64,56,56,],
[Async Backtrace]: ---
     /usr/lib/python3.9/runpy.py:197 <_run_module_as_main>
     /usr/lib/python3.9/runpy.py:87 <_run_code>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/test/test_resnet.py:151 <<module>>
     /usr/lib/python3.9/unittest/main.py:101 <__init__>
     /usr/lib/python3.9/unittest/main.py:271 <runTests>
     /usr/lib/python3.9/unittest/runner.py:176 <run>
     /usr/lib/python3.9/unittest/suite.py:84 <__call__>
     /usr/lib/python3.9/unittest/suite.py:122 <run>
     /usr/lib/python3.9/unittest/suite.py:84 <__call__>
     /usr/lib/python3.9/unittest/suite.py:122 <run>
     /usr/lib/python3.9/unittest/case.py:653 <__call__>
     /usr/lib/python3.9/unittest/case.py:593 <run>
     /usr/lib/python3.9/unittest/case.py:550 <_callTestMethod>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py:123 <inner>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/test/test_resnet.py:81 <test_resnet>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py:811 <__call__>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/test/test_resnet.py:34 <execute>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py:811 <__call__>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/models/resnet.py:152 <execute>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/models/resnet.py:142 <_forward_impl>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py:811 <__call__>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/nn.py:2054 <execute>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py:811 <__call__>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/models/resnet.py:49 <execute>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py:811 <__call__>
     /home/lfq/.local/lib/python3.9/site-packages/jittor/nn.py:847 <execute>
[Reason]: [f 0422 17:52:20.805405 96 helper_cuda.h:128] CUDA error at /home/lfq/.local/lib/python3.9/site-packages/jittor/src/mem/allocator/cuda_managed_allocator.cc:23  code=2( cudaErrorMemoryAllocation ) cudaMallocManaged(&ptr, size)

======================================================================
FAIL: test_resnet (__main__.TestResnetFp32)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lfq/.local/lib/python3.9/site-packages/jittor/__init__.py", line 123, in inner
    ret = func(*args, **kw)
  File "/home/lfq/.local/lib/python3.9/site-packages/jittor/test/test_resnet.py", line 133, in test_resnet
    assert jt.core.number_of_lived_vars() < 7000, jt.core.number_of_lived_vars()
AssertionError: 7450

----------------------------------------------------------------------
Ran 2 tests in 70.260s

FAILED (failures=1, errors=1)
```

**Comment by I6Redamancy** [comment]
This path may cause jittor found the wrong libs, please unset LD_LIBRARY_PATH and remove cuda lib path in Path. 还有想问一下这个warning具体应该如何解决，可以将wsl中的环境变量删到只有'/home/lfq/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64'吗

**Comment by I6Redamancy** [comment]
问题已解决，batch_size开小了，并不是环境配置的问题，可以将https://github.com/Jittor/jittor/blob/cac2b83a1c57855b1a578cfcf900dfa7a5b0c0c7/python/jittor/test/test_resnet.py#L52文件复制到本地，将batch_size改为1，如果能跑就没有问题。
支持国产深度学习框架！！！！
