### ISSUE TITLE
CUDA error code=702(cudaErrorLaunchTimeout) 

### ISSUE THREAD

**Issue by xiaosongshine** [Jittor/jittor#35]
CUDA error at /home/yss/miniconda3/envs/JT/lib/python3.7/site-packages/jittor/src/mem/allocator/cuda_dual_allocator.h:97 code=702(cudaErrorLaunchTimeout) "cudaLaunchHostFunc(0, &to_free_allocation, 0)"

**Comment by MenghaoGuo** [comment]
您好，首先感谢您使用 Jittor。
您对这个bug描述过于简单，我们也暂时看不出具体的原因。您能否方便提供一个可复现bug的脚本，或者提供一份更详尽的错误报告 ？

**Comment by MenghaoGuo** [comment]
您好，首先感谢您使用 Jittor。
您对这个bug描述过于简单，我们也暂时看不出具体的原因。您能否方便提供一个可复现bug的脚本，或者提供一份更详尽的错误报告 ？我们非常乐意为您解决这个问题。

**Comment by MenghaoGuo** [comment]
您好，首先感谢您使用 Jittor。
您对这个bug描述过于简单，我们也暂时看不出具体的原因。您能否方便提供一个可复现bug的脚本，或者提供一份更详尽的错误报告 ？我们非常希望为您解决这个问题。

**Comment by xiaosongshine** [comment]
我通过pip进行的安装：

运行 

> python3 -m jittor.test.test_example：

结果：

> Ran 1 test in 7.609s
> OK

运行

> # replace this var with your nvcc location 
> export nvcc_path="/usr/local/cuda/bin/nvcc" 
> # run a simple cuda test
> python3.7 -m jittor.test.test_cuda 

结果

> Ran 4 tests in 0.454s
> 
> OK (skipped=1)

运行：

> python3.7 -m jittor.test -v

结果

> 610 20 cuda_flags.cc:17] CUDA enabled.
> CUDA error at /home/yss/miniconda3/envs/JT/lib/python3.7/site-packages/jittor/src/executor.cc:398 code=700(cudaErrorIllegalAddress) "cudaDeviceSynchronize()" 

我在使用GPU训练时报错：

> CUDA error at /home/yss/miniconda3/envs/JT/lib/python3.7/site-packages/jittor/src/mem/allocator/cuda_dual_allocator.h:97 code=702(cudaErrorLaunchTimeout) "cudaLaunchHostFunc(0, &to_free_allocation, 0)"

**Comment by Jittor** [comment]
多谢反馈，请问您的`python3.7 -m jittor.test.test_resnet`运行结果正常吗。

**Comment by Jittor** [comment]
为了方便我们定位您的错误，可以提供`nvidia-smi`的信息吗？

**Comment by xiaosongshine** [comment]
电脑型号 小米笔记本 pro gtx   
nvidia-smi 信息：

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P0    N/A /  N/A |    360MiB /  4042MiB |     35%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1510      G   /usr/lib/xorg/Xorg                           192MiB |
|    0      1684      G   /usr/bin/gnome-shell                         119MiB |
|    0      2059      G   ...AAAAAAAAAAAAAAgAAAAAAAAA --shared-files    47MiB |
+-----------------------------------------------------------------------------+
```

**Comment by xiaosongshine** [comment]
> python3.7 -m jittor.test.test_resnet
测试应该是正常的，有输出结果，没有报错
```
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to /home/yss/.cache/jittor/dataset/mnist_data/train-images-idx3-ubyte.gz
100%|███████████████████████████▉| 9904128/9912422 [00:12<00:00, 1188193.85it/s]Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz to /home/yss/.cache/jittor/dataset/mnist_data/train-labels-idx1-ubyte.gz
32768it [00:01, 21180.46it/s]                                                   
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz to /home/yss/.cache/jittor/dataset/mnist_data/t10k-images-idx3-ubyte.gz
1654784it [00:02, 628632.71it/s]                                                
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz to /home/yss/.cache/jittor/dataset/mnist_data/t10k-labels-idx1-ubyte.gz
8192it [00:00, 12247.30it/s]                                                    
[i 0326 10:01:44.580538 92 cuda_flags.cc:17] CUDA enabled./4542 [00:00<?, ?it/s]
9920512it [01:16, 1188193.85it/s]                                               Train Epoch: 0 [0/600 (0%)]	Loss: 2.357862	Acc: 0.090000 	Time:87.738
```

**Comment by Jittor** [comment]
非常感谢您的反馈，可能是显存不足导致的，我这里为您定制了一个test_resnet.py, 用`python3.7 ./test_resnet.py` 运行即可，和原来的test相比，改小了batch size，并且关闭了一些空间换时间的优化，主要用于诊断是不是显存不足的问题，如果确实如此，我们会改进代码，尝试为您的机型做一些针对性的优化。
```
import jittor as jt
from jittor import nn, Module
from jittor.models import resnet
import numpy as np
import sys, os
import random
import math
import unittest
from jittor.test.test_reorder_tuner import simple_parser
from jittor.test.test_log import find_log_with_re
from jittor.dataset.mnist import MNIST
import jittor.transform as trans
import time

skip_this_test = False

class MnistNet(Module):
    def __init__(self):
        self.model = resnet.Resnet18()
        self.layer = nn.Linear(1000,10)
    def execute(self, x):
        x = self.model(x)
        x = self.layer(x)
        return x

@unittest.skipIf(skip_this_test, "skip_this_test")
class TestResnet(unittest.TestCase):
    @classmethod
    def setUpClass(self):
        # hyper-parameters
        self.batch_size = 10
        self.weight_decay = 0.0001
        self.momentum = 0.9
        self.learning_rate = 0.1
        # mnist dataset
        self.train_loader = MNIST(train=True, transform=trans.Resize(224)) \
            .set_attrs(batch_size=self.batch_size, shuffle=True)

    # setup random seed
    def setup_seed(self, seed):
        np.random.seed(seed)
        random.seed(seed)
        jt.seed(seed)

    @unittest.skipIf(not jt.has_cuda, "Cuda not found")
    @jt.flag_scope(use_cuda=1, use_stat_allocator=1)
    def test_resnet(self):
        self.setup_seed(1)
        loss_list=[]
        acc_list=[]
        mnist_net = MnistNet()
        global prev
        prev = time.time()
        SGD = nn.SGD(mnist_net.parameters(), self.learning_rate, self.momentum, self.weight_decay)

        for batch_idx, (data, target) in enumerate(self.train_loader):
            output = mnist_net(data)
            loss = nn.cross_entropy_loss(output, target)

            # train step
            with jt.log_capture_scope(
                log_silent=1,
                log_v=1, log_vprefix="op.cc=100,exe=10",
            ) as logs:
                SGD.step(loss)
                def callback(loss, output, target, batch_idx):
                    # print train info
                    global prev
                    pred = np.argmax(output, axis=1)
                    acc = np.sum(target==pred)/self.batch_size
                    loss_list.append(loss[0])
                    acc_list.append(acc)
                    print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}\tAcc: {:.6f} \tTime:{:.3f}'
                        .format(0, batch_idx, 600,1. * batch_idx / 6.0, loss[0], acc, time.time()-prev))
                    # prev = time.time()
                jt.fetch([loss, output, target], callback, batch_idx)
                jt.sync_all(True)

            log_conv = find_log_with_re(logs, 
                "Jit op key (not )?found: ((mkl)|(cudnn))_conv.*")
            log_matmul = find_log_with_re(logs, 
                "Jit op key (not )?found: ((mkl)|(cublas))_matmul.*")
            if batch_idx:
                assert len(log_conv)==59 and len(log_matmul)==6, (len(log_conv), len(log_matmul))

            mem_used = jt.flags.stat_allocator_total_alloc_byte \
                -jt.flags.stat_allocator_total_free_byte
            # assert mem_used < 4e9, mem_used
            # TODO: why bigger?
            assert mem_used < 5e9, mem_used
            # example log:
            # Train Epoch: 0 [0/100 (0%)]     Loss: 2.352903  Acc: 0.110000
            # Train Epoch: 0 [1/100 (1%)]     Loss: 2.840830  Acc: 0.080000
            # Train Epoch: 0 [2/100 (2%)]     Loss: 3.473594  Acc: 0.100000
            # Train Epoch: 0 [3/100 (3%)]     Loss: 3.131615  Acc: 0.200000
            # Train Epoch: 0 [4/100 (4%)]     Loss: 2.524094  Acc: 0.230000
            # Train Epoch: 0 [5/100 (5%)]     Loss: 7.780025  Acc: 0.080000
            # Train Epoch: 0 [6/100 (6%)]     Loss: 3.890721  Acc: 0.160000
            # Train Epoch: 0 [7/100 (7%)]     Loss: 6.370137  Acc: 0.140000
            # Train Epoch: 0 [8/100 (8%)]     Loss: 11.390827 Acc: 0.150000
            # Train Epoch: 0 [9/100 (9%)]     Loss: 21.598564 Acc: 0.080000
            # Train Epoch: 0 [10/100 (10%)]   Loss: 23.369165 Acc: 0.130000
            # Train Epoch: 0 [20/100 (20%)]   Loss: 4.804510  Acc: 0.100000
            # Train Epoch: 0 [30/100 (30%)]   Loss: 3.393924  Acc: 0.110000
            # Train Epoch: 0 [40/100 (40%)]   Loss: 2.286762  Acc: 0.130000
            # Train Epoch: 0 [50/100 (50%)]   Loss: 2.055014  Acc: 0.290000

            assert jt.core.number_of_lived_vars() < 3500

        jt.sync_all(True)
        assert np.mean(loss_list[-50:])<0.2
        
if __name__ == "__main__":
    unittest.main()

```

**Comment by xiaosongshine** [comment]
> 非常感谢您的反馈，可能是显存不足导致的，我这里为您定制了一个test_resnet.py, 用`python3.7 ./test_resnet.py` 运行即可，和原来的test相比，改小了batch size，并且关闭了一些空间换时间的优化，主要用于诊断是不是显存不足的问题，如果确实如此，我们会改进代码，尝试为您的机型做一些针对性的优化。
> 
> ```
> import jittor as jt
> from jittor import nn, Module
> from jittor.models import resnet
> import numpy as np
> import sys, os
> import random
> import math
> import unittest
> from jittor.test.test_reorder_tuner import simple_parser
> from jittor.test.test_log import find_log_with_re
> from jittor.dataset.mnist import MNIST
> import jittor.transform as trans
> import time
> 
> skip_this_test = False
> 
> class MnistNet(Module):
>     def __init__(self):
>         self.model = resnet.Resnet18()
>         self.layer = nn.Linear(1000,10)
>     def execute(self, x):
>         x = self.model(x)
>         x = self.layer(x)
>         return x
> 
> @unittest.skipIf(skip_this_test, "skip_this_test")
> class TestResnet(unittest.TestCase):
>     @classmethod
>     def setUpClass(self):
>         # hyper-parameters
>         self.batch_size = 10
>         self.weight_decay = 0.0001
>         self.momentum = 0.9
>         self.learning_rate = 0.1
>         # mnist dataset
>         self.train_loader = MNIST(train=True, transform=trans.Resize(224)) \
>             .set_attrs(batch_size=self.batch_size, shuffle=True)
> 
>     # setup random seed
>     def setup_seed(self, seed):
>         np.random.seed(seed)
>         random.seed(seed)
>         jt.seed(seed)
> 
>     @unittest.skipIf(not jt.has_cuda, "Cuda not found")
>     @jt.flag_scope(use_cuda=1, use_stat_allocator=1)
>     def test_resnet(self):
>         self.setup_seed(1)
>         loss_list=[]
>         acc_list=[]
>         mnist_net = MnistNet()
>         global prev
>         prev = time.time()
>         SGD = nn.SGD(mnist_net.parameters(), self.learning_rate, self.momentum, self.weight_decay)
> 
>         for batch_idx, (data, target) in enumerate(self.train_loader):
>             output = mnist_net(data)
>             loss = nn.cross_entropy_loss(output, target)
> 
>             # train step
>             with jt.log_capture_scope(
>                 log_silent=1,
>                 log_v=1, log_vprefix="op.cc=100,exe=10",
>             ) as logs:
>                 SGD.step(loss)
>                 def callback(loss, output, target, batch_idx):
>                     # print train info
>                     global prev
>                     pred = np.argmax(output, axis=1)
>                     acc = np.sum(target==pred)/self.batch_size
>                     loss_list.append(loss[0])
>                     acc_list.append(acc)
>                     print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}\tAcc: {:.6f} \tTime:{:.3f}'
>                         .format(0, batch_idx, 600,1. * batch_idx / 6.0, loss[0], acc, time.time()-prev))
>                     # prev = time.time()
>                 jt.fetch([loss, output, target], callback, batch_idx)
>                 jt.sync_all(True)
> 
>             log_conv = find_log_with_re(logs, 
>                 "Jit op key (not )?found: ((mkl)|(cudnn))_conv.*")
>             log_matmul = find_log_with_re(logs, 
>                 "Jit op key (not )?found: ((mkl)|(cublas))_matmul.*")
>             if batch_idx:
>                 assert len(log_conv)==59 and len(log_matmul)==6, (len(log_conv), len(log_matmul))
> 
>             mem_used = jt.flags.stat_allocator_total_alloc_byte \
>                 -jt.flags.stat_allocator_total_free_byte
>             # assert mem_used < 4e9, mem_used
>             # TODO: why bigger?
>             assert mem_used < 5e9, mem_used
>             # example log:
>             # Train Epoch: 0 [0/100 (0%)]     Loss: 2.352903  Acc: 0.110000
>             # Train Epoch: 0 [1/100 (1%)]     Loss: 2.840830  Acc: 0.080000
>             # Train Epoch: 0 [2/100 (2%)]     Loss: 3.473594  Acc: 0.100000
>             # Train Epoch: 0 [3/100 (3%)]     Loss: 3.131615  Acc: 0.200000
>             # Train Epoch: 0 [4/100 (4%)]     Loss: 2.524094  Acc: 0.230000
>             # Train Epoch: 0 [5/100 (5%)]     Loss: 7.780025  Acc: 0.080000
>             # Train Epoch: 0 [6/100 (6%)]     Loss: 3.890721  Acc: 0.160000
>             # Train Epoch: 0 [7/100 (7%)]     Loss: 6.370137  Acc: 0.140000
>             # Train Epoch: 0 [8/100 (8%)]     Loss: 11.390827 Acc: 0.150000
>             # Train Epoch: 0 [9/100 (9%)]     Loss: 21.598564 Acc: 0.080000
>             # Train Epoch: 0 [10/100 (10%)]   Loss: 23.369165 Acc: 0.130000
>             # Train Epoch: 0 [20/100 (20%)]   Loss: 4.804510  Acc: 0.100000
>             # Train Epoch: 0 [30/100 (30%)]   Loss: 3.393924  Acc: 0.110000
>             # Train Epoch: 0 [40/100 (40%)]   Loss: 2.286762  Acc: 0.130000
>             # Train Epoch: 0 [50/100 (50%)]   Loss: 2.055014  Acc: 0.290000
> 
>             assert jt.core.number_of_lived_vars() < 3500
> 
>         jt.sync_all(True)
>         assert np.mean(loss_list[-50:])<0.2
>         
> if __name__ == "__main__":
>     unittest.main()
> ```

感谢回复，我用你提供的代码，测试训练正常。

结果如下：

```
[i 0326 14:08:01.638224 44 cuda_flags.cc:17] CUDA enabled.
Train Epoch: 0 [0/600 (0%)]     Loss: 2.523785  Acc: 0.000000   Time:28.116
Train Epoch: 0 [1/600 (0%)]     Loss: 9.531067  Acc: 0.000000   Time:71.372
Train Epoch: 0 [2/600 (0%)]     Loss: 2.670616  Acc: 0.250000   Time:71.508
Train Epoch: 0 [3/600 (0%)]     Loss: 43.101418 Acc: 0.000000   Time:71.847
Train Epoch: 0 [4/600 (1%)]     Loss: 18.978456 Acc: 0.000000   Time:72.187
Train Epoch: 0 [5/600 (1%)]     Loss: 59.998772 Acc: 0.125000   Time:72.527
Train Epoch: 0 [6/600 (1%)]     Loss: 24.863476 Acc: 0.375000   Time:72.867
```

**Comment by zhouwy19** [comment]
> 
> 
> > 非常感谢您的反馈，可能是显存不足导致的，我这里为您定制了一个test_resnet.py, 用`python3.7 ./test_resnet.py` 运行即可，和原来的test相比，改小了batch size，并且关闭了一些空间换时间的优化，主要用于诊断是不是显存不足的问题，如果确实如此，我们会改进代码，尝试为您的机型做一些针对性的优化。
> > ```
> > import jittor as jt
> > from jittor import nn, Module
> > from jittor.models import resnet
> > import numpy as np
> > import sys, os
> > import random
> > import math
> > import unittest
> > from jittor.test.test_reorder_tuner import simple_parser
> > from jittor.test.test_log import find_log_with_re
> > from jittor.dataset.mnist import MNIST
> > import jittor.transform as trans
> > import time
> > 
> > skip_this_test = False
> > 
> > class MnistNet(Module):
> >     def __init__(self):
> >         self.model = resnet.Resnet18()
> >         self.layer = nn.Linear(1000,10)
> >     def execute(self, x):
> >         x = self.model(x)
> >         x = self.layer(x)
> >         return x
> > 
> > @unittest.skipIf(skip_this_test, "skip_this_test")
> > class TestResnet(unittest.TestCase):
> >     @classmethod
> >     def setUpClass(self):
> >         # hyper-parameters
> >         self.batch_size = 10
> >         self.weight_decay = 0.0001
> >         self.momentum = 0.9
> >         self.learning_rate = 0.1
> >         # mnist dataset
> >         self.train_loader = MNIST(train=True, transform=trans.Resize(224)) \
> >             .set_attrs(batch_size=self.batch_size, shuffle=True)
> > 
> >     # setup random seed
> >     def setup_seed(self, seed):
> >         np.random.seed(seed)
> >         random.seed(seed)
> >         jt.seed(seed)
> > 
> >     @unittest.skipIf(not jt.has_cuda, "Cuda not found")
> >     @jt.flag_scope(use_cuda=1, use_stat_allocator=1)
> >     def test_resnet(self):
> >         self.setup_seed(1)
> >         loss_list=[]
> >         acc_list=[]
> >         mnist_net = MnistNet()
> >         global prev
> >         prev = time.time()
> >         SGD = nn.SGD(mnist_net.parameters(), self.learning_rate, self.momentum, self.weight_decay)
> > 
> >         for batch_idx, (data, target) in enumerate(self.train_loader):
> >             output = mnist_net(data)
> >             loss = nn.cross_entropy_loss(output, target)
> > 
> >             # train step
> >             with jt.log_capture_scope(
> >                 log_silent=1,
> >                 log_v=1, log_vprefix="op.cc=100,exe=10",
> >             ) as logs:
> >                 SGD.step(loss)
> >                 def callback(loss, output, target, batch_idx):
> >                     # print train info
> >                     global prev
> >                     pred = np.argmax(output, axis=1)
> >                     acc = np.sum(target==pred)/self.batch_size
> >                     loss_list.append(loss[0])
> >                     acc_list.append(acc)
> >                     print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}\tAcc: {:.6f} \tTime:{:.3f}'
> >                         .format(0, batch_idx, 600,1. * batch_idx / 6.0, loss[0], acc, time.time()-prev))
> >                     # prev = time.time()
> >                 jt.fetch([loss, output, target], callback, batch_idx)
> >                 jt.sync_all(True)
> > 
> >             log_conv = find_log_with_re(logs, 
> >                 "Jit op key (not )?found: ((mkl)|(cudnn))_conv.*")
> >             log_matmul = find_log_with_re(logs, 
> >                 "Jit op key (not )?found: ((mkl)|(cublas))_matmul.*")
> >             if batch_idx:
> >                 assert len(log_conv)==59 and len(log_matmul)==6, (len(log_conv), len(log_matmul))
> > 
> >             mem_used = jt.flags.stat_allocator_total_alloc_byte \
> >                 -jt.flags.stat_allocator_total_free_byte
> >             # assert mem_used < 4e9, mem_used
> >             # TODO: why bigger?
> >             assert mem_used < 5e9, mem_used
> >             # example log:
> >             # Train Epoch: 0 [0/100 (0%)]     Loss: 2.352903  Acc: 0.110000
> >             # Train Epoch: 0 [1/100 (1%)]     Loss: 2.840830  Acc: 0.080000
> >             # Train Epoch: 0 [2/100 (2%)]     Loss: 3.473594  Acc: 0.100000
> >             # Train Epoch: 0 [3/100 (3%)]     Loss: 3.131615  Acc: 0.200000
> >             # Train Epoch: 0 [4/100 (4%)]     Loss: 2.524094  Acc: 0.230000
> >             # Train Epoch: 0 [5/100 (5%)]     Loss: 7.780025  Acc: 0.080000
> >             # Train Epoch: 0 [6/100 (6%)]     Loss: 3.890721  Acc: 0.160000
> >             # Train Epoch: 0 [7/100 (7%)]     Loss: 6.370137  Acc: 0.140000
> >             # Train Epoch: 0 [8/100 (8%)]     Loss: 11.390827 Acc: 0.150000
> >             # Train Epoch: 0 [9/100 (9%)]     Loss: 21.598564 Acc: 0.080000
> >             # Train Epoch: 0 [10/100 (10%)]   Loss: 23.369165 Acc: 0.130000
> >             # Train Epoch: 0 [20/100 (20%)]   Loss: 4.804510  Acc: 0.100000
> >             # Train Epoch: 0 [30/100 (30%)]   Loss: 3.393924  Acc: 0.110000
> >             # Train Epoch: 0 [40/100 (40%)]   Loss: 2.286762  Acc: 0.130000
> >             # Train Epoch: 0 [50/100 (50%)]   Loss: 2.055014  Acc: 0.290000
> > 
> >             assert jt.core.number_of_lived_vars() < 3500
> > 
> >         jt.sync_all(True)
> >         assert np.mean(loss_list[-50:])<0.2
> >         
> > if __name__ == "__main__":
> >     unittest.main()
> > ```
> 
> 感谢回复，我用你提供的代码，测试训练正常。
> 
> 结果如下：
> 
> ```
> [i 0326 14:08:01.638224 44 cuda_flags.cc:17] CUDA enabled.
> Train Epoch: 0 [0/600 (0%)]     Loss: 2.523785  Acc: 0.000000   Time:28.116
> Train Epoch: 0 [1/600 (0%)]     Loss: 9.531067  Acc: 0.000000   Time:71.372
> Train Epoch: 0 [2/600 (0%)]     Loss: 2.670616  Acc: 0.250000   Time:71.508
> Train Epoch: 0 [3/600 (0%)]     Loss: 43.101418 Acc: 0.000000   Time:71.847
> Train Epoch: 0 [4/600 (1%)]     Loss: 18.978456 Acc: 0.000000   Time:72.187
> Train Epoch: 0 [5/600 (1%)]     Loss: 59.998772 Acc: 0.125000   Time:72.527
> Train Epoch: 0 [6/600 (1%)]     Loss: 24.863476 Acc: 0.375000   Time:72.867
> ```

非常开心您的问题解决，如果后续使用还有什么问题，欢迎联系我们。感谢您的Jittor的关注。
